name: 'Redocly Lint & Bundle'
inputs:
  working-directory:
    default: '.'
  cache:
    default: 'npm'
runs:
  using: "composite"
  steps:
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: ${{ inputs.cache }}
        cache-dependency-path: ${{ inputs.working-directory }}/package-lock.json

    - name: Install & Run Build
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        npm ci
        npm test
        npm run build