stages:
  - synchronisation

include:
  - component: $CI_SERVER_FQDN/knowledge-integration/pipeline-utils/gitlab-components/git-sync/branch-sync@main
    inputs:
      ssh_key: "${SSH_KEY_VAR}"
      target_url: ssh://git@github.com/k-int/github-actions.git
      branches:
        - main
        - test # A place to put actions we're testing out
      additional_push_opts: "--force" # This is DESTRUCTIVE, github WILL be overwritten

# Override the component's underlying job to target your runner
branch-sync:
  stage: synchronisation
  tags:
    - ki-onprem