name: Folio OpenAPI Master Orchestrator

on:
  workflow_call:
    inputs:
      redocly-dir:
        type: string
        required: true
        description: "The directory containing the Redocly build config files"
      spec-dir:
        type: string
        required: true
        description: "The pristine directory containing ONLY your target openapi spec files"
      openapi-filename:
        type: string
        required: true
        description: "Filename of the bundled spec file outputted by Redocly"
      allowed-deploy-branch:
        type: string
        required: false
        default: "main master"
        description: "Space-separated list of branches allowed to deploy to S3. (DO NOT leave permanently modified)"
    secrets:
      S3_ACCESS_KEY_ID:
        required: true
      S3_SECRET_ACCESS_KEY:
        required: true
      GITLAB_DEPLOY_USER:
        required: true
      GITLAB_DEPLOY_TOKEN:
        required: true

jobs:
  run-redocly-bundle:
    name: Redocly compilation stage
    uses: k-int/github-actions/.github/workflows/redocly-build.yml@main
    with:
      redocly-dir: ${{ inputs.redocly-dir }}
      spec-dir: ${{ inputs.spec-dir }}
      openapi-filename: ${{ inputs.openapi-filename }}
      artifact-name: 'open-api-spec'
    secrets:
      GITLAB_DEPLOY_USER: ${{ secrets.GITLAB_DEPLOY_USER }}
      GITLAB_DEPLOY_TOKEN: ${{ secrets.GITLAB_DEPLOY_TOKEN }}

  run-folio-toolchain:
    name: Folio toolchain stage
    needs: run-redocly-bundle
    uses: k-int/github-actions/.github/workflows/folio-api-tools-pipeline.yml@main
    with:
      spec-dir: ${{ inputs.spec-dir }}
      artifact-name: 'open-api-spec'
      allowed-deploy-branch: ${{ inputs.allowed-deploy-branch }}
    secrets:
      S3_ACCESS_KEY_ID: ${{ secrets.S3_ACCESS_KEY_ID }}
      S3_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_ACCESS_KEY }}