name: Hello World Example Action

on:
  workflow_call:
    secrets:
      GITLAB_DEPLOY_USER:
        required: true
      GITLAB_DEPLOY_TOKEN:
        required: true

jobs:
  # --- JOB 1 ---
  job-hello:
    name: Echo Hello Task
    runs-on: ubuntu-latest
    steps:
      - name: Initialize Vault Scripts
        uses: ./.github/actions/clone-vault

      - name: Execute Echo Hello Action
        uses: ./central-scripts/actions/hello-world/echo-hello

  # --- JOB 2 ---
  job-world:
    name: Echo World Task
    runs-on: ubuntu-latest
    steps:
      - name: Initialize Vault Scripts
        uses: ./.github/actions/clone-vault

      - name: Execute Echo World Action
        uses: ./central-scripts/actions/hello-world/echo-world

  # --- JOB 3 ---
  job-combine:
    name: Combine Artifacts Task
    runs-on: ubuntu-latest
    needs: [job-hello, job-world]
    steps:
      - name: Initialize Vault Scripts
        uses: ./.github/actions/clone-vault

      - name: Execute Combine Action
        uses: ./central-scripts/actions/hello-world/combine