name: Redocly Build & Push

on:
  workflow_call:
    inputs:
      redocly-dir:
        type: string
        required: true
        description: "Directory containing the package.json and Redocly setup (e.g., docs/API/config)"
      spec-dir:
        type: string
        required: true
        description: "Dedicated directory where specs reside (e.g., docs/API/yamls)"
      openapi-filename:
        type: string
        required: true
        description: "The name of the compiled master spec file (e.g., agreements.yaml)"
      artifact-name:
        type: string
        required: false
        default: ""
    secrets:
      GITLAB_DEPLOY_USER:
        required: true
      GITLAB_DEPLOY_TOKEN:
        required: true

jobs:
  bundle-spec:
    name: Bundle & auto-commit Redocly spec
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v5
        with:
          ref: ${{ github.head_ref || github.ref_name }}

      - name: Run Redocly action
        uses: k-int/github-actions/.github/actions/openapi/redocly-build@main
        with:
          working-directory: ${{ inputs.redocly-dir }}

      - name: Auto-commit bundled specification
        if: github.event_name == 'pull_request'
        uses: k-int/github-actions/.github/actions/commit-directly@main
        with:
          tracked_files: "${{ inputs.spec-dir }}/${{ inputs.openapi-filename }}"
          commit_message: "chore: auto-update bundled openapi specification"
          deploy_user: ${{ secrets.GITLAB_DEPLOY_USER }}
          deploy_token: ${{ secrets.GITLAB_DEPLOY_TOKEN }}

      - name: Upload bundled spec directory artifact
        if: inputs.artifact-name != ''
        uses: actions/upload-artifact@v5
        with:
          name: ${{ inputs.artifact-name }}
          path: ${{ inputs.spec-dir }}/