name: Centralized Gradle SBOM Generation

on:
  workflow_call:
    inputs:
      gradle_project_path:
        type: string
        required: false
        default: '.'
      syft_args:
        type: string
        required: false
        default: ''
      tracked_files:
        type: string
        required: false
        default: 'cdx-bom.json'
      commit_lockfiles:
        type: string
        required: false
        default: 'false'
    secrets:
      GITLAB_DEPLOY_USER:
        required: true
      GITLAB_DEPLOY_TOKEN:
        required: true

jobs:
  # JOB 1: Spin up and execute the Syft analysis
  generate-sbom:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Application Repository
        uses: actions/checkout@v5

      - name: Initialize action scripts
        uses: k-int/github-actions/.github/actions/clone-action-scripts@main
        with:
          deploy_user: ${{ secrets.GITLAB_DEPLOY_USER }}
          deploy_token: ${{ secrets.GITLAB_DEPLOY_TOKEN }}

      - name: Generate SBOM Data
        uses: ./central-scripts/actions/sbom-generation/gradle-syft-sbom
        with:
          gradle_project_path: ${{ inputs.gradle_project_path }}
          syft_args: ${{ inputs.syft_args }}

      # Saving the newly generated assets
      - name: Share Generated Compliance Assets
        uses: actions/upload-artifact@v5
        with:
          name: compiled-sbom-assets
          path: |
            ${{ inputs.tracked_files }}
            **/gradle.lockfile
          if-no-files-found: ignore
          retention-days: 1

  # JOB 2: Download assets, match differentials, and push to host repo
  commit-sbom:
    needs: generate-sbom
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write # NECESSARY for auto-merge of SBOM
    steps:
      - name: Checkout Application Repository
        uses: actions/checkout@v5
        with:
          persist-credentials: true # Crucial for the subsequent git push step

      - name: Initialize action scripts
        uses: k-int/github-actions/.github/actions/clone-action-scripts@main
        with:
          deploy_user: ${{ secrets.GITLAB_DEPLOY_USER }}
          deploy_token: ${{ secrets.GITLAB_DEPLOY_TOKEN }}

      # Pull the assets generated by Job 1 directly into this runner's workspace
      - name: Retrieve Generated Compliance Assets
        uses: actions/download-artifact@v5
        with:
          name: compiled-sbom-assets

      - name: Upload and Sync BOM
        uses: ./central-scripts/actions/sbom-generation/commit-sbom-files
        with:
          tracked_files: ${{ inputs.tracked_files }}
          commit_lockfiles: ${{ inputs.commit_lockfiles }}